package constant

const (
	CfgRootFolder                 = ".tkube"
	CfgFolder                     = "config"
	ResourcesFolder               = "resources"
	TmpFolder                     = "tmp"
	IsoFilesFolder                = "iso"
	IsoMountDir                   = "/mnt/tkube"
	EtcdPkiFolder                 = "/etc/etcd/pki"
	EtcdCaCertPath                = "/etc/etcd/pki/ca.crt"
	EtcdCaKeyPath                 = "/etc/etcd/pki/ca.key"
	EtcdClientKeyPath             = "/etc/etcd/pki/apiserver-etcd-client.key"
	EtcdClientCertPath            = "/etc/etcd/pki/apiserver-etcd-client.crt"
	EtcdRecoveryCertFolder        = "recovery/etcd-certs"
	DeploymentCfgName             = "deployment"
	DefaultCfgType                = "yaml"
	DefaultContainerdSandboxImage = "pause:3.9"
	DefaultDockerAptRepoAddress   = "https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable"
	DefaultDockerAptRepoKey       = "https://download.docker.com/linux/ubuntu/gpg"
	DefaultDockerYumRepoAddress   = "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
	DefaultDockerYumRepoKey       = "https://download.docker.com/linux/centos/gpg"
	DefaultEtcdUrl                = "default"
	DefaultKubeAptRepoAddress     = "https://pkgs.k8s.io/core:/stable:/v{version}/deb/ /"
	DefaultKubeAptRepoKey         = "https://pkgs.k8s.io/core:/stable:/v{version}/deb/Release.key"
	DefaultKubeYumRepoAddress     = "https://pkgs.k8s.io/core:/stable:/v{version}/rpm/"
	DefaultKubeYumRepoKey         = "https://pkgs.k8s.io/core:/stable:/v{version}/rpm/repodata/repomd.xml.key"
	DefaultPodSubnet              = "10.244.0.0/16"
	DefaultKubeImageRegistry      = "registry.k8s.io"
	DefaultCalicoUrl              = "default"
	DefaultHelmUrl                = "default"
	DefaultHelmfileUrl            = "default"
)
